### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by jlkoran** [uchicagotechteam/CS4All-Map-SchoolLocator#4]
Cause unclear ¯\_(ツ)_/¯

**Comment by cnwalker** [comment]
I was bored in game construction, so I took another look at this guy. The url thing from earlier wasn't the issue - it was from a function that wasn't used.

The real issue is that the function getGoogleAPIKey() returns different keys when you're on your local or production. The production API key is restricted to certain IPs, so the autocomplete request would return a 403 error. I changed the production key to the local key, and things seem to work now.

Try visiting the site in another browser or deleting your chrome cached images and files and reloading the page (if you use chrome). The map should work just like the CPS map.
